# makefile for client

DEBUG   =@
RM      =rm
CC      =gcc
ECHO    =@echo
CFLAGS  =-Wall -O3 -D_LINUX_
LDFLAGS =

EXE     =me7romtool
SRC     =$(notdir $(foreach dir, ., $(wildcard $(dir)/*.c)))
LIBS    =

include makefile.common
